### ISSUE TITLE
Reversing a stack using another stack. 

### ISSUE THREAD

**Issue by Sid200026** [Bhupesh-V/30-seconds-of-cpp#292]
The repo doesn't contain any code for reversing a stack. The same has been added in the pull request.
GH-233

**Comment by Ranner198** [comment]
Do you have a preference if it should be recursive or not?

**Comment by Sid200026** [comment]
In my PR, I have reversed it without recursion.

**Comment by ranaakash** [comment]
Hi @Sid200026 
Is this issue still open ?
I can contribute then..
