### ISSUE TITLE
search implementation in c++

### ISSUE THREAD

**Issue by adigeak** [Bhupesh-V/30-seconds-of-cpp#300]
What to implement search as it is in the todo list.
Assign it to me if nobody is working.
#Hacktoberfest

**Comment by Ranner198** [comment]
Looking for any particular search algorithm? is it for demo purposes or something for searching in the webpage or etc?

**Comment by adigeak** [comment]
i wanna to apply linear  and fibonacci search in a array

**Comment by adigeak** [comment]
refer to my pr #301
