### ISSUE TITLE
Missing reference to the implementation of set:lower_bound

### ISSUE THREAD

**Issue by gafeol** [Bhupesh-V/30-seconds-of-cpp#324]
Although the explanation for lower_bound (for a set) was added to the repository, no references for it were added.

**To Reproduce**
Accessing the main README file:
<img width="266" alt="image" src="https://user-images.githubusercontent.com/12179028/67035522-19743280-f11a-11e9-8d5f-3a06d4308f4b.png">

README from "set" folder:
<img width="342" alt="image" src="https://user-images.githubusercontent.com/12179028/67035635-504a4880-f11a-11e9-85b0-d0e470b9f735.png">

**Expected behavior**
A reference for the <a href="https://github.com/gafeol/30-seconds-of-cpp/blob/master/set/lower_bound.md">lower_bound file</a> should be shown in these lists.

**Comment by Bhupesh-V** [comment]
All the updates are done automatically (this is stated in Contributing Guidelines too)
I will fix this personally after reviewing the PRs
