### ISSUE TITLE
Add Run Code Links in existing code snippets

### ISSUE THREAD

**Issue by Bhupesh-V** [Bhupesh-V/30-seconds-of-cpp#36]
Add Runnable links of the code below the example.
Use link name [Run Code]() which links to a Online C++ complier conatining the example code.
Use **_Rextester_** as the Online C++ Compiler (If you have a better suggesstion please comment).
 > Follow below steps to generate the Run Code Link.

1. Go to [Rextester](https://rextester.com/l/cpp_online_compiler_gcc)
2. Copy or write the example code.
3. Run the code (hit F8) , see if you face any problems
4. Save the code with the followng title format 
            `<algo_name>_30-Seconds-of-C++`
5. A permanent link will be generated , copy that 
6. Submit a PR which contains the [Run Code]() Link just below the example.

> Comment any doubts, suggesstions.

**Comment by sdmg15** [comment]
Yes I think it's good.
 And I think the fact that  you want to create a separate file for each code snippet is not that too good. I think it's better to have all in on place + run-able  code link.

**Comment by Bhupesh-V** [comment]
> Yes I think it's good.
> And I think the fact that you want to create a separate file for each code snippet is not that too good. I think it's better to have all in on place + run-able code link.
> 
> Another point is that I think we need to make the code uniform (Either using `std::` or not, but warning before ) and prefer using predefined `algorithm`

I guess using `std::` would be rather safe than `using namespace std;` what do you suggest ?

**Comment by Bhupesh-V** [comment]
> Yes I think it's good.
> And I think the fact that you want to create a separate file for each code snippet is not that too good. I think it's better to have all in on place + run-able code link.

Yeah you are right , I would remove the extra directories of different headers

**Comment by sdmg15** [comment]
Yes I suggest putting `std::`

**Comment by vsin12** [comment]
Are any of these tasks still available ? I am new to open-source and would like to start contributing.
I see that this issue is open, but I do not see any run-code links missing.

**Comment by Blahblahblahsomething** [comment]
Is this issue still open?

**Comment by Bhupesh-V** [comment]
@vsin12 @Blahblahblahsomething you can contribute sample code and give a PR in the snippets directory.
see some examples on how to add sample code

**Comment by Blahblahblahsomething** [comment]
Thank you.

**Comment by Harshwp** [comment]
Is this issue still open? I would like to contribute

**Comment by akhilkh2000** [comment]
Is this issue still open?

**Comment by ashwani-rathee** [comment]
Is this issue still open?

**Comment by Bhupesh-V** [comment]
> Is this issue still open?

Yes

**Comment by marcinky** [comment]
Hi! It looks like this issue is still open. I'm a newbie who would like to contribute.

**Comment by YersiniaP** [comment]
Hello there, I am also new to OS and would like to contribute to this project. As per the instructions, I will get the example code to run using Rextester and paste the permanent link below the snippet before submitting a PR.

**Comment by Alka-git12** [comment]
May I work on this project?

**Comment by dbejanishvili** [comment]
[onlinegdb](https://www.onlinegdb.com/online_c++_compiler) seems to have compilers that work with functions, some of which rextester doesn't have support for.

**Comment by mouryac9** [comment]
I would like to work on this issue.

**Comment by AmitBhagat3301** [comment]
I would also like on work on this issue.

**Comment by AlexMunozPino** [comment]
Hey! I would like to work on this issue as well

**Comment by aditi-goyal-257** [comment]
I would like to contribute, is this issue still open?

**Comment by AryanNayak** [comment]
Hey, can I contribute to the issue?

**Comment by abhishekd358** [comment]
Hey, I already Submitted a pull request regarding the  rotate_copy algorithm.Now I want to add heap_sort in algorithm . Can you assign the issue to me ? .
