### ISSUE TITLE
Include other concepts of c++

### ISSUE THREAD

**Issue by harshraj22** [Bhupesh-V/30-seconds-of-cpp#398]
The repo serves a fantastic guide to introduce new comers with the standard library of c++. It would be even great if we could add other lesser known( or used ) features of c++ here. 
* Suggestions:
   * [ ] Object Oriented Programming (not only inheritance, but also interesting topics like method chaining and [this pointer](https://www.learncpp.com/cpp-tutorial/8-8-the-hidden-this-pointer/))
   * [ ] Templates and variadic templates ( quite interesting ) and discussion about issues ( dos and donts ) with using templates with Classes
   * [ ] Lambda functions 
<h4> And more such interesting and rarely features of c++ </h4>

**Comment by Delta456** [comment]
I don't think that this is the aim of the repo.

**Comment by Bhupesh-V** [comment]
@harshraj22 meanwhile as @Delta456 said it not the aim of repo for "now".
But we will soon plan out to include things you said, you can join the discord server for suggesting anything new.
Meanwhile I will open an issue thread where everyone can suggest Advanced C++ topics :fire:
