### ISSUE TITLE
std::set does not have a member function "contains".

### ISSUE THREAD

**Issue by Shiv-sharma-111** [Bhupesh-V/30-seconds-of-cpp#487]
[for reference](https://stackoverflow.com/questions/42532550/why-does-stdset-not-have-a-contains-member-function)

**Comment by hbinderup94** [comment]
It does since C++20: 
https://en.cppreference.com/w/cpp/container/set/contains

Your reference is 3 years old and now have an updated response: https://stackoverflow.com/a/61430051
