### ISSUE TITLE
Looking for Maintainer/Collaborator

### ISSUE THREAD

**Issue by Bhupesh-V** [Bhupesh-V/30-seconds-of-cpp#490]
I have been maintaining this project for a long time now and I think I am not able respond quickly to new PRs thus driving away future contributors.

If you have already contributed to 30 Seconds of C++ before feel free to comment below, if you are willing to be a potential maintainer and collaborator.

> The goal of 30C++ is to make sure C++ is easier to learn by providing quick explanations of STL, while driving the beginner friendly OpenSource Contribution

**Comment by Delta456** [comment]
I can help

**Comment by insaaniManav** [comment]
Hey bhupesh this is Manav sethi from ilugd I can also help in maintaining

**Comment by Bhupesh-V** [comment]
Thanks for reaching out guys :fire: , I will be deciding this in a few days

**Comment by Bhupesh-V** [comment]
Thanks @Delta456 and @insaaniManav for reaching out. For now I have added @Delta456 as a maintainer.
@insaaniManav please be in touch, we will require more collaborators during programs like hacktoberfest. Meanwhile make sure you join the Discord server

**Comment by insaaniManav** [comment]
Sure thanks @bhupeshv :D
