### ISSUE TITLE
State of this project

### ISSUE THREAD

**Issue by Mikadore** [Bhupesh-V/30-seconds-of-cpp#565]
22 open issues, some months old. 58 open pull requests. The `README`s do not coincide with existing code/files.
Is this project maintained at all?

**Comment by Bhupesh-V** [comment]
Hello, @Mikadore 👋🏽 Thanks for your concern about the state of 30C++.
Sorry for not actively maintaining, I have been equipped with my college life (which is btw over).

The review process will be slow but linear from now on so please be patient if you have contributed before.


Thanks
