### ISSUE TITLE
Missing is_sorted() function in algorithm.

### ISSUE THREAD

**Issue by ayush-pr0** [Bhupesh-V/30-seconds-of-cpp#665]
Recently I have just checked this repo, I found the is_sorted() function is missing. This is_sorted() function which is related to the Algorithm.  Can I make my first contribution by adding this function?

**Comment by kgpjay** [comment]
Hi, I am new to this project and want to contribute. Can you please guide me from where should I start.

**Comment by lAmanl** [comment]
Im new to open source and would like to contribute in this project

**Comment by Sayantan19** [comment]
Hi! I would like to contribute to this project. Could you please assign to me this part?
