### ISSUE TITLE
Bug for_each_n incorrect comment

### ISSUE THREAD

**Issue by MiloATH** [Bhupesh-V/30-seconds-of-cpp#92]
**Describe the bug**
In algorithm/for_each_n.md, there is a comment `// Will output, 3 2 3 9` which is incorrect. This program will print out "3 2 ".

**To Reproduce**
1. Go to algorithm/for_each_n.md

**Expected behavior**
Comment should read: `// Will output, "3 2 "`

**Compiler (please complete the following information):**
 - OS: MacOS
 - Compiler Version [e.g. gcc 8.2]: Apple LLVM version 10.0.0 (clang-1000.11.45.5)

**Additional context**
Maybe the example could be changed to something like the one used at [cppreference](https://en.cppreference.com/w/cpp/algorithm/for_each_n).

**Comment by Bhupesh-V** [comment]
Hey @MiloATH can you provide screenshots of the same
I am having issues with my C++ version
I guess the code is working fine on LLVM

**Comment by MiloATH** [comment]
<img width="485" alt="Screen Shot " src="https://user-images.githubusercontent.com/12666146/60766050-8b87a680-a058-11e9-83ff-f5b7c2071c37.png">
