### ISSUE TITLE
Bug: The links in the README.md pages for each header file folder don't work

### ISSUE THREAD

**Issue by bermani** [Bhupesh-V/30-seconds-of-cpp#97]
**Describe the bug**
All of the links in the README files in each of the header file folders are broken.

**To Reproduce**
1. Go to [algorithm](https://github.com/Bhupesh-V/30-seconds-of-cpp/tree/master/algorithm), [list](https://github.com/Bhupesh-V/30-seconds-of-cpp/tree/master/list) or any of the other header file folders.
2. View contents and try to click on any link
3. They don't do anything

**Expected behavior**
I expect them to take me to the correct Markdown file. I think your update_readme.py script should also update the READMEs in each of the subfolders.

**Comment by Bhupesh-V** [comment]
Hey @bermani actually the README(s) in different folders are just present to keep a record of all the functions/methods which are yet to be implemented in _30C++_.
They currently do not have any purpose.

**Comment by bermani** [comment]
Oh ok I see, maybe those READMEs can list which functions are implemented and which ones are not implemented yet? And the ones that are already implemented can have links? I can work on the update_readme.py script to update the READMEs and submit a PR if that's a design choice you want to make, or this issue can just be closed if you want to leave them as is.

**Comment by Bhupesh-V** [comment]
Yeah that's a good idea
we could use emojis (:heavy_check_mark:  :x:  )to indicate which of them are implemented or not.
If you want you can work on that :+1:
