### ISSUE TITLE
For loop efficiency

### ISSUE THREAD

**Issue by sdmg15** [Bhupesh-V/30-seconds-of-cpp#99]
Hello,
We should prefer pre-incrementation (++i, --i )  over post-incrementation ( i++, i-- ) in traditional for loop, until they will make a difference in the result. Pre-incrementation is actually more efficient than post-incrementation as in the post incrementation will need addition copy of the data.

**Comment by manav1234** [comment]
ya sir completely agree with you

**Comment by Bhupesh-V** [comment]
@sdmg15 yes that's true I will add this in the [CONTRIBUTING](https://github.com/Bhupesh-V/30-seconds-of-cpp/blob/master/CONTRIBUTING.md) guidelines. :+1:
